### ISSUE TITLE
How do we compile the shaders?

### ISSUE THREAD

**Issue by DethRaid** [Alenett/TES-Reloaded-Shaders-NEW#1]
I'm trying to modify the shadow shader. I've changed `ShadowsExteriors.fx.hlsl` in my `Data/Shaders/NewVegasReloaded/Shadows` folder but I don't see those changes when I play the game

Additionally, is there a way to recompile and reload all the shaders without restarting the game?

**Comment by Alenett** [comment]
Yes. The shader must be recompiled. In that case it is an effect, so
activate the option compile effects in the ini. The effects will be
compiled when you start the game and every time you disable and
re-enabled/reload the shader. To do that use the ingame menu (in the case
of post process shadows you can set the quality to 0 and get back to -1 to
reload/reactivate the post process shadows) and it will be recompiled and
loaded.

Use the effects inside the package and not the ones from the repos. They
could not be the last version. The last version is always in the package.

Il dom 31 gen 2021, 21:24 David Dubois <notifications@github.com> ha
scritto:

**Comment by DethRaid** [comment]
I enabled compiling shaders and compiling effects. My startup times got noticibly longer. However, I didn't notice any changes to the in-game shadows, and the compiled `.fx` files in my `Data/Shaders/NewVegasReloaded/Shadows` folder haven't changed

How do I open the menu? The config file says it's keycode "24" but I can't figure out what key on my keyboard that is

**Comment by DethRaid** [comment]
Just checked the New Vegas Reloaded log. I don't see anything about compiling the shader I changed - `ShadowsExteriors.fx.hlsl`

**Comment by Alenett** [comment]
You did not follow the istructions.
1. Enable compile effects (not shaders)
2. ShadowsExteriors.fx.hlsl is not used at default, it is used for post processing shadows. So you must enable the post process shadowing (set quality to -1 for exteriors)
3. To know how TESR works, join the official forum and/or the discord channel you can find on the site (www.tesreloaded.com), do not open here these type of requests. You need to know how TESR work before working on it.
